//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLDJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flow
    {
        public int flow_id { get; set; }
        public string flow_num { get; set; }
        public string flow_order { get; set; }
        public string flow_type { get; set; }
        public string flow_dept { get; set; }
        public string flow_founder { get; set; }
        public string flow_stime { get; set; }
        public string flow_etime { get; set; }
        public string flow_state { get; set; }
    }
}
