//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLDJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flow_QJHC
    {
        public string QJHC_flowid { get; set; }
        public Nullable<int> QJHC_personid { get; set; }
        public string QJHC_pname { get; set; }
        public string QJHC_pdept { get; set; }
        public string QJHC_IfZZXY { get; set; }
        public string QJHC_IfGZYJ { get; set; }
        public string QJHC_IfMFZY { get; set; }
        public string QJHC_DeptOpitxt { get; set; }
    }
}
