//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLDJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class flow_DevYB
    {
        public string DevYB_flowid { get; set; }
        public Nullable<int> DevYB_personid { get; set; }
        public string DevYB_pname { get; set; }
        public Nullable<int> DevYB_introid1 { get; set; }
        public string DevYB_introname1 { get; set; }
        public Nullable<int> DevYB_introid2 { get; set; }
        public string DevYB_introname2 { get; set; }
        public string DevYB_pdept { get; set; }
        public string DevYB_PWtxt { get; set; }
        public string DevYB_ZStxt { get; set; }
        public string DevYB_DOptxt { get; set; }
        public string DevYB_DWOptxt { get; set; }
        public string DevYB_Trprtxt { get; set; }
    }
}
