//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLDJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flow> flow { get; set; }
        public virtual DbSet<flow_Devmem> flow_Devmem { get; set; }
        public virtual DbSet<flow_DevYB> flow_DevYB { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<flow_NewYXDY> flow_NewYXDY { get; set; }
        public virtual DbSet<flow_NewZGDY> flow_NewZGDY { get; set; }
        public virtual DbSet<flow_QJHC> flow_QJHC { get; set; }
        public virtual DbSet<person_YXDY> person_YXDY { get; set; }
    }
}
