//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLDJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DJXTEntities2 : DbContext
    {
        public DJXTEntities2()
            : base("name=DJXTEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flow_Devmem> flows_Devmem { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<flow> flows { get; set; }
    }
}
