//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLDJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int person_id { get; set; }
        public string person_name { get; set; }
        public string person_sex { get; set; }
        public string person_birth { get; set; }
        public string person_CJGZdate { get; set; }
        public string person_ZGDYdate { get; set; }
        public string person_YBDYdate { get; set; }
        public string person_JJFZdate { get; set; }
        public string person_eduback { get; set; }
        public string person_degree { get; set; }
        public string person_college { get; set; }
        public string person_phonenum { get; set; }
        public string person_email { get; set; }
        public string person_dept { get; set; }
        public string person_plstatus { get; set; }
    }
}
