//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLDJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_YXDY
    {
        public int YXDY_personid { get; set; }
        public string YXDY_date { get; set; }
        public Nullable<int> YXDY_iftest { get; set; }
        public string YXDY_ltdate { get; set; }
    }
}
